### ISSUE TITLE
weather.yahooapis.com doesn't working anymore

### ISSUE THREAD

**Issue by maozturk** [fedy2/yahoo-weather-java-api#7]
I don't know exactly why but the url that was used this application is not working anymore. This application should support YQL instead.

**Comment by crea-doo** [comment]
Yahoo has changed the API but there is already a branch that supports YQL (look [here](https://github.com/fedy2/yahoo-weather-java-api/tree/yql)).
I've forked and released a version based on that branch as long as there is no "official" update that fixes the problem: [https://github.com/crea-doo/yahoo-weather-java-api](https://github.com/crea-doo/yahoo-weather-java-api)

**Comment by fedy2** [comment]
Hi @maozturk, version 2.0.0 of yahoo-weather-java-api has been released with support of YQL. You can use it with the following dependency declaration:
<dependency>
     <groupId>com.github.fedy2</groupId>
     <artifactId>yahoo-weather-java-api</artifactId>
     <version>2.0.0</version>
</dependency>

**Comment by fedy2** [comment]
@crea-doo, really thanks for you work. I've reported your changes in the main repository and released a new version of the library.

**Comment by crea-doo** [comment]
@fedy2, you're welcome. I've now deleted my fork...
